setwd("/Users/binay/Downloads/Data scientist toolbox/cleaning data")
library(data.table)
DT<-fread("./data/household_power_consumption.txt", sep=";", stringsAsFactors = FALSE, na.strings = "?", header=TRUE)
DT$Date<-as.Date(DT$Date, format="%d/%m/%Y")
DT_subset<-subset(DT, Date>="2007-02-01" & Date<="2007-02-02")
DT_subset$Time<-paste(DT_subset$Date, DT_subset$Time, sep=" ")
png(file="plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(DT_subset$Time, DT_subset$Global_active_power, type="n", ylab="Global Active Power", xlab="")
lines(DT_subset$Time, DT_subset$Global_active_power)
plot(DT_subset$Time, DT_subset$Voltage, ylab="Voltage", type="n", xlab="datetime")
lines(DT_subset$Time, DT_subset$Voltage)
plot(DT_subset$Time,  DT_subset$Sub_metering_1, type = "n", ylab="Energy sub metering", xlab="")
lines(DT_subset$Time, DT_subset$Sub_metering_1)
lines(DT_subset$Time, DT_subset$Sub_metering_2, col="red")
lines(DT_subset$Time, DT_subset$Sub_metering_3, col="blue")
legend("topright", lty=(1), col=c("black", "red", "blue"), cex=0.75, bty="n", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(DT_subset$Time, DT_subset$Global_reactive_power, type="n", ylab="Global_reactive_power", xlab="datetime")
lines(DT_subset$Time, DT_subset$Global_reactive_power)
dev.off()
