setwd("/Users/binay/Downloads/Data scientist toolbox/cleaning data")
library(data.table)
DT<-fread("./data/household_power_consumption.txt", sep=";", stringsAsFactors = FALSE, na.strings = "?", header=TRUE)
DT$Date<-as.Date(DT$Date, format="%d/%m/%Y")
DT_subset<-subset(DT, Date>="2007-02-01" & Date<="2007-02-02")
DT_subset$Time<-paste(DT_subset$Date, DT_subset$Time, sep=" ")
DT_subset$Time<-as.POSIXct(DT_subset$Time, format="%Y-%m-%d %H:%M:%S")
png(file="plot2.png", width = 480, height = 480)
plot(DT_subset$Time, DT_subset$Global_active_power, type="n", ylab="Global Active Power(kilowatts)", xlab="" )
lines(DT_subset$Time, DT_subset$Global_active_power)
dev.off()